// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzxKvJ5OIg0vJJUr8_Wccm1BMOkl7hBdc',
    appId: '1:950008936120:web:3959cb5d76f8e9f7ba664d',
    messagingSenderId: '950008936120',
    projectId: 'loginapp-5b857',
    authDomain: 'loginapp-5b857.firebaseapp.com',
    storageBucket: 'loginapp-5b857.appspot.com',
    measurementId: 'G-E0KJ9BZT65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBLi7LGcwjGW_KYZgsfwvVCgzg9x77TZk',
    appId: '1:950008936120:android:f6afec6e7b58c456ba664d',
    messagingSenderId: '950008936120',
    projectId: 'loginapp-5b857',
    storageBucket: 'loginapp-5b857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHpadw3KU2TQq6V6idbbGpfYXpgotEFsc',
    appId: '1:950008936120:ios:2bdf78caca159766ba664d',
    messagingSenderId: '950008936120',
    projectId: 'loginapp-5b857',
    storageBucket: 'loginapp-5b857.appspot.com',
    iosBundleId: 'com.example.expencetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHpadw3KU2TQq6V6idbbGpfYXpgotEFsc',
    appId: '1:950008936120:ios:2bdf78caca159766ba664d',
    messagingSenderId: '950008936120',
    projectId: 'loginapp-5b857',
    storageBucket: 'loginapp-5b857.appspot.com',
    iosBundleId: 'com.example.expencetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzxKvJ5OIg0vJJUr8_Wccm1BMOkl7hBdc',
    appId: '1:950008936120:web:012af15e5cb28996ba664d',
    messagingSenderId: '950008936120',
    projectId: 'loginapp-5b857',
    authDomain: 'loginapp-5b857.firebaseapp.com',
    storageBucket: 'loginapp-5b857.appspot.com',
    measurementId: 'G-ZFBM4BLP2C',
  );

}